package com.bsquare.core.common.enums

enum class EmitType {
    AppVersion,
    BackendError,
    NetworkError,
    IntroStatus,
    Navigate,
    Loading,
    Inform,
    FeaturesItem,
    LeadsItem,
    LeadsDetails,
    LeadAdded,
    LeadRemoved,
    AddNewLead,
    FollowItem,
    UpcomingFollow,
    OverdueFollow,
    DoneFollow,
    TaskDetailData,
    getResponse,
    leadFilterDetails,
    userDetails,
    AddActivityDetails,
    AddNotesDetails,
    addActivity,
}